server:
  port: ${PORT:5000}

base-url: /api

spring:
  profiles:
    active: ${PROFILE:dev}

jwt:
  secret: YzNlNjVkZTQ3YjEyNWY5MWVmNWE2MjQyMzRiYmE4NTRmNGY0N2EzMDc3ZTIwYTUxNjM3ZGI0YTgyZWYyNjA0Mg==

rollbar:
  token: {ROLLBAR_TOKEN:}